### ISSUE TITLE
(1.20.4) Pause menu button order is messed up

### ISSUE THREAD

**Issue by DuncanRuns** [Minecraft-Java-Edition-Speedrunning/FastReset#4]
While in game, pressing escape and then tab should focus onto the "Back to Game" button.
But w/ fastreset installed, it focuses on the menu.quitWorld button instead, or it focuses on "Save and Quit to Title" if the button position is set to "replace s&q".

Occurs in 1.20.4 but may affect more versions.

**Comment by tildejustin** [comment]
new guis are ugh

**Comment by tildejustin** [comment]
i did some clever stuff to avoid writing a third inject for the s&q button but i didn't forsee this issue with replacing the button widget in the adder...tbh i'm not sure how to manipulate 1.19+ guis to fix this since i don't think you can do floating widgets with the adder nor change the id, although the second might be possible.  
https://github.com/Minecraft-Java-Edition-Speedrunning/fastreset/blob/87d58e580a153722764ae5f9b710d68483a697f5/src/main/java/fast_reset/client/mixin/GameMenuMixin.java#L23-L34

**Comment by tildejustin** [comment]
fixed
